// ── STATE ──
const profile = {
  income: '60to80',
  networks: new Set(['visa','mc']),
  chexy: 'yes',
  rogers: 'no',
  goal: 'cashback',
  grocers: new Set(),
  activeBanking: new Set(), // computed by optimizer — do not set directly
  willingToDD: 'no',
  minBal: 0,
  assetBanks: new Set(),    // banks where user has $100K+ assets (unlocks fee waivers for free)
  maxcards: '4',
  amexAcceptance: 0.8,      // fraction of spend where Amex is accepted (applied to Amex card net value)
  perks: { flights: null, intl: null, flightClass: null, lounges: null, hotelNights: null, nexus: null, airline: null },
};

// ── ALL CARDS DATA ──
const CARDS = [
  // ── CASHBACK ──
  {
    id: 'cibc-div',
    name: 'CIBC Dividend Visa Infinite',
    network: 'visa', type: 'cashback', fee: 120, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['cibc'],
    rates: { groceries: 0.04, dining: 0.02, gas: 0.04, recurring: 0.02, rent: 0.02, other: 0.01, travel: 0.01 },
    caps: {},
    notes: '4% groceries & gas, no caps. Works at No Frills, FreshCo, Iqbal Foods. Fee waived with CIBC Smart Plus.',
    warning: null, amexBlock: false,
  },
  {
    id: 'td-cashback',
    name: 'TD Cash Back Visa Infinite',
    network: 'visa', type: 'cashback', fee: 139, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['td'],
    rates: { groceries: 0.03, dining: 0.01, gas: 0.03, recurring: 0.03, rent: 0.03, other: 0.01, travel: 0.01 },
    caps: { groceries: 15000/12, gas: 15000/12, recurring: 15000/12 },
    capYearly: { groceries: true, gas: true, recurring: true },
    notes: '3% groceries/gas/recurring ($15K/yr annual cap each = $1,250/mo). Roadside assist. Fee waived with TD All-Inclusive.',
    warning: null, amexBlock: false,
  },
  {
    id: 'scotia-momentum',
    name: 'Scotia Momentum Visa Infinite',
    network: 'visa', type: 'cashback', fee: 120, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['scotia'],
    rates: { groceries: 0.04, dining: 0.02, gas: 0.02, recurring: 0.04, rent: 0.04, other: 0.01, travel: 0.01 },
    caps: {},
    capGroups: [{ cats: ['groceries', 'recurring', 'rent'], monthly: 2083, yearly: true }],
    notes: '4% groceries & recurring (great for rent via Chexy). $25K/yr combined cap across groceries + recurring + rent (~$2,083/mo total). Only 2% gas — weakness vs CIBC. Fee waived with Scotia Ultimate Package.',
    warning: null, amexBlock: false,
  },
  {
    id: 'bmo-cashback',
    name: 'BMO CashBack World Elite',
    network: 'mc', type: 'cashback', fee: 120, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: ['bmo'],
    rates: { groceries: 0.05, dining: 0.01, gas: 0.03, recurring: 0.02, rent: 0.02, other: 0.01, travel: 0.01 },
    caps: { groceries: 500 },
    notes: '5% groceries (capped $500/mo), 4% transit, 3% gas, 2% recurring. Dining only 1% — weak. Fee waived with BMO Premium Plan.',
    warning: 'Chexy is Visa-only — use Casa for rent with this card', amexBlock: false,
  },
  {
    id: 'neo-we',
    name: 'Neo World Elite',
    network: 'mc', type: 'cashback', fee: 125, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.05, dining: 0.01, gas: 0.03, recurring: 0.04, rent: 0.01, other: 0.01, travel: 0.01 },
    caps: { groceries: 1000, recurring: 500 },
    notes: '5% groceries ($1K/mo cap), 4% recurring ($500/mo cap — subscriptions/digital only, not rent), 3% gas. Rent via Casa earns 1% base rate.',
    warning: 'Chexy is Visa-only — use Casa for rent with this card', amexBlock: false,
  },
  {
    id: 'simplycash',
    name: 'SimplyCash Preferred',
    network: 'amex', type: 'cashback', fee: 119.88, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.04, dining: 0.0125, gas: 0.02, recurring: 0.0125, rent: 0, other: 0.0125, travel: 0.0125 },
    caps: { groceries: 2500 },
    capYearly: { groceries: true },
    notes: '4% groceries (capped $30K/yr spend = $1,200/yr cashback max), 2% gas, 1.25% everything else. No income requirement.',
    warning: 'Amex — not accepted at No Frills, FreshCo, Iqbal Foods, or Costco', amexBlock: true,
  },
  {
    id: 'simplii',
    name: 'Simplii Cash Back Visa',
    network: 'visa', type: 'cashback', fee: 0, minIncome: 0,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.015, dining: 0.04, gas: 0.015, recurring: 0.015, rent: 0.015, other: 0.005, travel: 0.005 },
    caps: { dining: 5000/12 }, capYearly: { dining: true },
    notes: 'Best dining card in Canada at 4%, zero annual fee. $5K/yr annual dining cap ($416/mo). Payout once/year in January.',
    warning: null, amexBlock: false,
  },
  {
    id: 'rogers-we',
    name: 'Rogers Red World Elite',
    network: 'mc', type: 'cashback', fee: 0, minIncome: 80000,
    chexyOk: false, rogersReq: true, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.03, dining: 0.03, gas: 0.03, recurring: 0.03, rent: 0.03, other: 0.03, travel: 0.03 },
    caps: {},
    notes: '3% cashback on all purchases for Rogers/Fido/Shaw customers. 2.5% FX fee applies (net 0.5% on international spend). No annual fee, no caps.',
    warning: 'Chexy is Visa-only — use Casa for rent with this card', amexBlock: false,
  },
  {
    id: 'desjardins',
    name: 'Desjardins Cash Back WE',
    network: 'mc', type: 'cashback', fee: 100, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.04, dining: 0.03, gas: 0.01, recurring: 0.01, rent: 0.01, other: 0.01, travel: 0.01 },
    caps: {},
    notes: '4% groceries, 3% dining/entertainment/transit. Dragon Pass lounge access (3 visits/yr).',
    warning: 'Chexy is Visa-only — use Casa for rent with this card', amexBlock: false,
  },
  {
    id: 'mbna-we',
    name: 'MBNA World Elite Mastercard',
    network: 'mc', type: 'cashback', fee: 120, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.0451, dining: 0.0451, gas: 0.009, recurring: 0.0451, rent: 0.009, other: 0.009, travel: 0.009 },
    pts: { groceries: 5.5, dining: 5.5, gas: 1.1, recurring: 5.5, rent: 1.1, other: 1.1, travel: 1.1 },
    caps: { groceries: 4167, dining: 4167, recurring: 4167 },
    capYearly: { groceries: true, dining: true, recurring: true },
    notes: '5pts/$1 on groceries, dining & recurring (each capped $50K/yr = $4,167/mo). 1pt/$1 base on everything else. +10% birthday bonus = 5.5pts effective on bonus cats. MBNA Rewards redeem for statement credit at ~0.82cpp — effectively cashback. Rent does not earn at bonus rate.',
    warning: 'Rent earns only 1x (base rate) — does not code as a recurring bonus category', amexBlock: false,
    cpp: { stmt: 0.82, avgTravel: 0.82 },
    loyalty: { program: 'mbna-rewards', label: 'MBNA Rewards', transfersTo: [], isolated: true },
  },
  {
    id: 'ws-infinite',
    name: 'Wealthsimple Visa Infinite',
    network: 'visa', type: 'cashback', fee: 240, minIncome: 60000,
    chexyOk: true, rogersReq: false, wsReq: true, noFx: true, feeWaivedBy: ['ws'],
    rates: { groceries: 0.02, dining: 0.02, gas: 0.02, recurring: 0.02, rent: 0.02, other: 0.02, travel: 0.02 },
    caps: {},
    notes: '$240/yr fee — waived with Wealthsimple Premium ($4K/mo direct deposit or $100K+ assets). No FX fees. 2% flat everywhere. No spending caps.',
    warning: 'Fee waiver requires $4K/mo direct deposit to Wealthsimple (Premium tier).',
    amexBlock: false,
  },
  // ── POINTS ──
  {
    id: 'cobalt',
    name: 'Amex Cobalt',
    network: 'amex', type: 'points', fee: 191.88, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.05, dining: 0.05, gas: 0.02, recurring: 0.01, rent: 0, other: 0.01, travel: 0.01 },
    pts: { groceries: 5, dining: 5, gas: 2, recurring: 1, rent: 0, other: 1, travel: 1 },
    caps: {},
    capGroups: [{ cats: ['groceries', 'dining'], monthly: 2500 }],
    notes: '5x MR on food & dining = 5% at 1cpp (statement) or ~10% at 2cpp (Aeroplan biz class). Combined $2,500/mo cap across groceries + dining (12,500 pts/mo total). 1:1 transfer to Aeroplan/Avios.',
    warning: 'Amex — not accepted at Costco, No Frills, or Iqbal Foods',
    amexBlock: true, cpp: { stmt: 1.0, avgTravel: 2.0 },
    loyalty: { program: 'mr', label: 'Amex MR', transfersTo: ['aeroplan', 'avios', 'asia-miles', 'ba', 'flying-blue'] },
    cppBreakdown: [
      { label: 'Economy — Continental (Aeroplan/Avios)', cpp: 1.3 },
      { label: 'Economy — International (Aeroplan/Avios/Asia Miles)', cpp: 1.6 },
      { label: 'Business — Continental (Aeroplan)', cpp: 2.2 },
      { label: 'Business — International (Aeroplan/Avios/Asia Miles)', cpp: 2.8 },
      { label: 'Statement credit (MR → 1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'nb-we',
    name: 'National Bank World Elite',
    network: 'mc', type: 'points', fee: 150, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.05, dining: 0.05, gas: 0.02, recurring: 0.02, rent: 0.02, other: 0.02, travel: 0.02 },
    pts: { groceries: 5, dining: 5, gas: 2, recurring: 2, rent: 2, other: 2, travel: 2 },
    caps: {},
    capGroups: [{ cats: ['groceries', 'dining'], monthly: 2083, yearly: true }],
    notes: '5pts/$1 on groceries & restaurants (combined $25K/yr cap across groceries + dining). 3 lounge visits/yr. 2% on gas, recurring & travel. Has 2.5% FX fee — not ideal for international spend.',
    warning: 'Chexy is Visa-only — use Casa for rent with this card',
    amexBlock: false, cpp: { stmt: 1.0, avgTravel: 1.0 },
    loyalty: { program: 'ala-carte', label: 'NB À la carte', transfersTo: [], isolated: true },
  },
  {
    id: 'scotia-gold',
    name: 'Scotia Gold Amex',
    network: 'amex', type: 'points', fee: 120, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: true, feeWaivedBy: ['scotia'],
    rates: { groceries: 0.0402, dining: 0.0402, gas: 0.0134, recurring: 0.0134, rent: 0, other: 0.0134, travel: 0.0134 },
    pts: { groceries: 6, dining: 6, gas: 2, recurring: 2, rent: 0, other: 2, travel: 2 },
    caps: {},
    notes: '6x Scene+ on groceries (incl. Sobeys, FreshCo, IGA, Safeway), dining, and entertainment (4.02% at 0.67cpp). No FX fees. Fee waived with Scotia Ultimate. Max value via Apply to Travel (1cpp = 6%).',
    warning: 'Amex — limited acceptance. Scene+ best redeemed via Scotia Travel portal (1cpp).',
    amexBlock: true, cpp: { stmt: 0.67, avgTravel: 1.0 },
    loyalty: { program: 'scene+', label: 'Scene+', transfersTo: [], isolated: false },
  },
  // ── TRAVEL ──
  {
    id: 'td-aeroplan',
    name: 'TD Aeroplan Visa Infinite',
    network: 'visa', type: 'travel', fee: 139, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['td'],
    rates: { groceries: 0.015, dining: 0.015, gas: 0.015, recurring: 0.015, rent: 0.015, other: 0.01, travel: 0.03 },
    pts: { groceries: 1, dining: 1, gas: 1, recurring: 1, rent: 1, other: 1, travel: 2 },
    caps: {},
    notes: 'Free first checked bag on Air Canada flights (you + up to 8 companions). NEXUS rebate $100/48mo. Fee waived with TD All-Inclusive. Best value if you fly Air Canada regularly.',
    warning: 'Low earn rate (1x–2x). Free bag perk is Air Canada flights only — limited value for WestJet/BA flyers.',
    amexBlock: false, cpp: { stmt: 1.0, avgTravel: 1.5 },
    loyalty: { program: 'aeroplan', label: 'Aeroplan', transfersTo: [] },
    cppBreakdown: [
      { label: 'Economy — Continental (AC / Star Alliance)', cpp: 1.3 },
      { label: 'Economy — International (AC / Star Alliance)', cpp: 1.5 },
      { label: 'Business — Continental (AC / Star Alliance)', cpp: 2.2 },
      { label: 'Business — International (AC / Star Alliance)', cpp: 2.8 },
      { label: 'Statement credit (1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'cibc-aeroplan',
    name: 'CIBC Aeroplan Visa Infinite',
    network: 'visa', type: 'travel', fee: 139, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['cibc'],
    rates: { groceries: 0.015, dining: 0.015, gas: 0.015, recurring: 0.015, rent: 0.015, other: 0.01, travel: 0.03 },
    pts: { groceries: 1, dining: 1, gas: 1, recurring: 1, rent: 1, other: 1, travel: 2 },
    caps: {},
    notes: 'Free first checked bag on Air Canada flights (you + up to 8 companions). Ecopass bonus. Same perks as TD Aeroplan — choose based on banking relationship. Fee waived with CIBC Smart Plus.',
    warning: 'Low earn rate (1x–2x). Free bag perk is Air Canada flights only — limited value for WestJet/BA flyers.',
    amexBlock: false, cpp: { stmt: 1.0, avgTravel: 1.5 },
    loyalty: { program: 'aeroplan', label: 'Aeroplan', transfersTo: [] },
    cppBreakdown: [
      { label: 'Economy — Continental (AC / Star Alliance)', cpp: 1.3 },
      { label: 'Economy — International (AC / Star Alliance)', cpp: 1.5 },
      { label: 'Business — Continental (AC / Star Alliance)', cpp: 2.2 },
      { label: 'Business — International (AC / Star Alliance)', cpp: 2.8 },
      { label: 'Statement credit (1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'scotia-passport',
    name: 'Scotiabank Passport Visa Infinite',
    network: 'visa', type: 'travel', fee: 150, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: true, feeWaivedBy: ['scotia'],
    rates: { groceries: 0.0201, dining: 0.0201, gas: 0.0067, recurring: 0.0067, rent: 0.0067, other: 0.0067, travel: 0.0067 },
    pts: { groceries: 3, dining: 3, gas: 1, recurring: 1, rent: 1, other: 1, travel: 1 },
    caps: {},
    notes: '3x Scene+ on groceries/dining/entertainment (2.01% at 0.67cpp). 1pt/$1 on everything else (0.67%). 6 free lounge visits/yr. No FX fees. Fee waived with Scotia Ultimate.',
    warning: 'Scene+ best redeemed via Scotia Travel portal (1cpp). FX travel earns only 1pt/$1.',
    amexBlock: false, cpp: { stmt: 0.67, avgTravel: 1.0 },
    loyalty: { program: 'scene+', label: 'Scene+', transfersTo: [], isolated: false },
  },
  {
    id: 'rbc-avion',
    name: 'RBC Avion Visa Infinite',
    network: 'visa', type: 'travel', fee: 120, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['rbc'],
    rates: { groceries: 0.0125, dining: 0.0125, gas: 0.0125, recurring: 0.0125, rent: 0.0125, other: 0.0125, travel: 0.0175 },
    pts: { groceries: 1.25, dining: 1.25, gas: 1.25, recurring: 1.25, rent: 1.25, other: 1.25, travel: 1.75 },
    caps: {},
    notes: '1.25x Avion everywhere (1.75x on travel). Transfers to Aeroplan, Avios, Asia Miles, BA. Fee waived with RBC VIP Banking.',
    warning: 'Value comes from transfer partner flexibility, not everyday earn rate.',
    amexBlock: false, cpp: { stmt: 1.0, avgTravel: 1.5 },
    loyalty: { program: 'avion', label: 'RBC Avion', transfersTo: ['aeroplan', 'avios', 'asia-miles', 'ba'] },
    cppBreakdown: [
      { label: 'Economy — Continental (Avios/Aeroplan)', cpp: 1.3 },
      { label: 'Economy — International (Avios/Asia Miles)', cpp: 1.5 },
      { label: 'Business — Continental (Aeroplan)', cpp: 2.0 },
      { label: 'Business — International (Avios/Asia Miles)', cpp: 2.5 },
      { label: 'Statement credit (1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'amex-aeroplan',
    name: 'Amex Aeroplan',
    network: 'amex', type: 'travel', fee: 120, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.015, dining: 0.0225, gas: 0.015, recurring: 0.015, rent: 0, other: 0.015, travel: 0.015 },
    pts: { groceries: 1, dining: 1.5, gas: 1, recurring: 1, rent: 0, other: 1, travel: 1 },
    caps: {},
    notes: '1pt/$1 everywhere (1.5% at avgTravel cpp), 1.5pt on eligible dining (2.25%). Bonus: 2x on direct Air Canada purchases. No income requirement.',
    warning: 'Amex — limited acceptance. No free bags unlike Visa Aeroplan cards.',
    amexBlock: true, cpp: { stmt: 1.0, avgTravel: 1.5 },
    loyalty: { program: 'aeroplan', label: 'Aeroplan', transfersTo: [] },
    cppBreakdown: [
      { label: 'Economy — Continental (AC / Star Alliance)', cpp: 1.3 },
      { label: 'Economy — International (AC / Star Alliance)', cpp: 1.5 },
      { label: 'Business — Continental (AC)', cpp: 2.2 },
      { label: 'Business — International (AC / Star Alliance)', cpp: 2.8 },
      { label: 'Statement credit (1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'amex-plat',
    name: 'Amex Platinum',
    network: 'amex', type: 'travel', fee: 799, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    perksValue: 600,
    rates: { groceries: 0.03, dining: 0.03, gas: 0.01, recurring: 0.01, rent: 0, other: 0.01, travel: 0.02 },
    pts: { groceries: 3, dining: 3, gas: 1, recurring: 1, rent: 0, other: 1, travel: 2 },
    caps: {},
    notes: '3x MR on dining & groceries, 2x on travel. $200 travel credit + $200 FHR hotel credit + NEXUS rebate + unlimited Centurion & Priority Pass lounge access. $600 credit value used in net calculation.',
    warning: 'High $799 fee — only worthwhile if you maximize all credits and lounge access.',
    amexBlock: true, cpp: { stmt: 1.0, avgTravel: 1.5 },
    loyalty: { program: 'mr', label: 'Amex MR', transfersTo: ['aeroplan', 'avios', 'asia-miles', 'ba', 'flying-blue'] },
    cppBreakdown: [
      { label: 'Economy — Continental (Aeroplan/Avios)', cpp: 1.3 },
      { label: 'Economy — International (Aeroplan/Avios/Asia Miles)', cpp: 1.6 },
      { label: 'Business — Continental (Aeroplan)', cpp: 2.2 },
      { label: 'Business — International (Aeroplan/Avios/Asia Miles)', cpp: 2.8 },
      { label: 'Hotel — FHR / Amex Travel', cpp: 1.4 },
      { label: 'Statement credit (MR → 1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'westjet-rbc',
    name: 'WestJet RBC World Elite Mastercard',
    network: 'mc', type: 'cashback', fee: 119, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: ['rbc'],
    rates: { groceries: 0.015, dining: 0.015, gas: 0.015, recurring: 0.015, rent: 0.015, other: 0.015, travel: 0.02 },
    caps: {},
    notes: '1.5% WestJet dollars everywhere, 2% on WestJet flights & vacation packages. Free first checked bag on WestJet flights only (you + up to 8 companions). Annual round-trip companion voucher for WestJet flights (significant value for WestJet flyers). Fee waived with RBC VIP Banking.',
    warning: 'WestJet dollars can only be redeemed on WestJet flights & packages — limited value if you don\'t fly WestJet regularly. Free bag and companion voucher apply to WestJet flights only.',
    amexBlock: false,
    loyalty: { program: 'westjet', label: 'WestJet Rewards', transfersTo: [], isolated: false },
  },
  {
    id: 'tangerine-mc',
    name: 'Tangerine Money-Back Mastercard',
    network: 'mc', type: 'cashback', fee: 0, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.02, dining: 0.02, gas: 0.005, recurring: 0.005, rent: 0.005, other: 0.005, travel: 0.005 },
    caps: {},
    notes: 'Choose 2 categories at 2% (3 categories with Tangerine banking). Ideal as a no-fee companion: pick categories your primary card doesn\'t cover. 0.5% base everywhere else.',
    warning: 'Best paired with a specialist card — use it for your 2 weakest categories on your main card. Cashback deposited to Tangerine savings only.',
    amexBlock: false,
  },
  {
    id: 'amex-gold',
    name: 'Amex Gold Rewards Card',
    network: 'amex', type: 'points', fee: 250, minIncome: 0,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.02, dining: 0.02, gas: 0.02, recurring: 0.01, rent: 0, other: 0.01, travel: 0.02 },
    pts: { groceries: 2, dining: 2, gas: 2, recurring: 1, rent: 0, other: 1, travel: 2 },
    caps: {},
    notes: '2x MR on groceries, dining, gas & travel. $100 annual travel credit (hotels/flights via Amex Travel). 4 complimentary lounge passes/yr. 1:1 transfers to Aeroplan, Avios, Asia Miles.',
    warning: 'Amex — not accepted everywhere. Lower earn than Cobalt on food (2x vs 5x) but more coverage across gas & travel with the annual travel credit.',
    amexBlock: true,
    cpp: { stmt: 1.0, avgTravel: 2.0 },
    loyalty: { program: 'mr', label: 'Amex MR', transfersTo: ['aeroplan', 'avios', 'asia-miles', 'ba', 'flying-blue'] },
    cppBreakdown: [
      { label: 'Economy — Continental (Aeroplan/Avios)', cpp: 1.3 },
      { label: 'Economy — International (Aeroplan/Avios/Asia Miles)', cpp: 1.6 },
      { label: 'Business — Continental (Aeroplan)', cpp: 2.2 },
      { label: 'Business — International (Aeroplan/Avios/Asia Miles)', cpp: 2.8 },
      { label: 'Statement credit (MR → 1cpp)', cpp: 1.0 },
    ],
  },
  {
    id: 'cibc-aventura',
    name: 'CIBC Aventura Visa Infinite',
    network: 'visa', type: 'travel', fee: 139, minIncome: 60000,
    chexyOk: true, rogersReq: false, noFx: false, feeWaivedBy: ['cibc'],
    rates: { groceries: 0.015, dining: 0.015, gas: 0.015, recurring: 0.01, rent: 0.01, other: 0.01, travel: 0.02 },
    pts: { groceries: 1.5, dining: 1.5, gas: 1.5, recurring: 1, rent: 1, other: 1, travel: 2 },
    caps: {},
    notes: '1.5x Aventura on groceries/gas/dining, 1x everything else, 2x on travel via CIBC Rewards. Redeem for any flight at 1cpp via CIBC travel portal. No airline transfers. Fee waived with CIBC Smart Plus.',
    warning: 'Aventura points only redeem via CIBC travel portal — no Aeroplan/Avios transfers. Value locked to 1cpp.',
    amexBlock: false,
    cpp: { stmt: 1.0, avgTravel: 1.0 },
    loyalty: { program: 'aventura', label: 'CIBC Aventura', transfersTo: [], isolated: false },
  },
  {
    id: 'pc-financial',
    name: 'PC Financial World Elite Mastercard',
    network: 'mc', type: 'cashback', fee: 120, minIncome: 80000,
    chexyOk: false, rogersReq: false, noFx: false, feeWaivedBy: [],
    rates: { groceries: 0.03, dining: 0.01, gas: 0.015, recurring: 0.01, rent: 0.01, other: 0.01, travel: 0.01 },
    caps: {},
    notes: '30 PC Optimum points per $ at Loblaws/Shoppers (= ~3% toward free groceries). 20pts/$ at Loblaw gas bars. 10pts/$ elsewhere (= ~1%). Points only redeemable at Loblaws/Shoppers/PC Travel — restricted cashback.',
    warning: 'PC Optimum redeemable at Loblaws/Shoppers Drug Mart only. Best if you regularly shop at Loblaws, Zehrs, No Frills, Shoppers, or Esso/Mobil with PC.',
    amexBlock: false,
  },
  {
    id: 'brim-we',
    name: 'Brim World Elite Mastercard',
    network: 'mc', type: 'travel', fee: 199, minIncome: 80000,
    chexyOk: true, rogersReq: false, noFx: true, feeWaivedBy: [],
    rates: { groceries: 0.015, dining: 0.015, gas: 0.01, recurring: 0.01, rent: 0.01, other: 0.01, travel: 0.02 },
    pts: { groceries: 1.5, dining: 1.5, gas: 1, recurring: 1, rent: 1, other: 1, travel: 2 },
    caps: {},
    notes: 'No FX fees on all purchases. 1.5% on groceries/dining, 2% on travel, 1% everywhere else. Points transfer 1:1 to Air France/KLM Flying Blue. Priority Pass lounge access (6 visits/yr). $10/month in Brim bonus credits.',
    warning: 'Points primarily valuable via Flying Blue (SkyTeam). High annual fee vs value requires Flying Blue redemptions for business-class flights.',
    amexBlock: false,
    cpp: { stmt: 1.0, avgTravel: 1.8 },
    loyalty: { program: 'flying-blue', label: 'Air France/KLM Flying Blue', transfersTo: [] },
    cppBreakdown: [
      { label: 'Economy — Continental (Flying Blue)', cpp: 1.3 },
      { label: 'Economy — International (Flying Blue)', cpp: 1.8 },
      { label: 'Business — Continental (Flying Blue)', cpp: 2.2 },
      { label: 'Business — International (Flying Blue)', cpp: 2.8 },
      { label: 'Statement credit (1cpp)', cpp: 1.0 },
    ],
  },
];

const CARD_BENEFITS = {
  'cibc-div': [
    'Emergency travel medical — up to 10 days per trip (must charge full trip cost to card)',
    'Trip cancellation & interruption — up to $2,500/person cancellation, $5,000 interruption',
    'Mobile device insurance — up to $1,000 if purchased on card',
    'Purchase protection — 90 days against theft or accidental damage',
    'Extended warranty — doubles manufacturer warranty up to 1 additional year',
    'Rental car loss/damage insurance — waives collision damage waiver at rental desks',
  ],
  'td-cashback': [
    'Emergency travel medical — up to 10 days per trip',
    'Trip cancellation & interruption insurance included',
    'TD Auto Club roadside assistance — towing, battery boost, flat tire, lockout',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'scotia-momentum': [
    'Emergency travel medical — up to 10 days per trip',
    'Trip cancellation & interruption insurance',
    'Mobile device insurance — up to $1,000 replacement/repair',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'bmo-cashback': [
    'Emergency travel medical — up to 8 days per trip (up to 64 days if 65+)',
    'Trip cancellation & interruption coverage',
    'Mobile device insurance included',
    'Purchase protection (90 days) & extended warranty (+1 yr)',
    'Rental car collision/loss damage insurance',
  ],
  'neo-we': [
    'Purchase protection — 120 days against theft or damage (longer than most cards)',
    'Extended warranty — adds 2 extra years (best-in-class warranty extension)',
    'Mobile device insurance for phones purchased on card',
    'Rental car collision/loss damage insurance',
  ],
  'simplycash': [
    'Emergency travel medical insurance',
    'Trip cancellation, interruption & flight delay insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'simplii': [
    'Emergency travel medical — up to 10 days per trip',
    'Trip interruption insurance',
    'Purchase protection & extended warranty',
  ],
  'rogers-we': [
    'Emergency travel medical — up to 15 days per trip (under 65)',
    'Trip cancellation & interruption insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
    'Note: 3% cashback on FX purchases offsets the 2.5% FX fee, netting +0.5% on foreign spend',
  ],
  'desjardins': [
    'Dragon Pass lounge access — 3 free visits/yr at 1,300+ airport lounges worldwide',
    'Emergency travel medical insurance',
    'Trip interruption coverage',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'mbna-we': [
    '10% birthday bonus points every year — applied automatically on your birthday month',
    '24/7 roadside assistance — towing, fuel delivery, lockout, flat tire',
    'Emergency travel medical insurance',
    'Trip cancellation & interruption insurance',
    'Purchase protection & extended warranty',
  ],
  'ws-infinite': [
    'No foreign transaction fees — save 2.5% on all international purchases',
    'Emergency travel medical insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
    'Requires Wealthsimple Premium ($10/mo or $100K+ assets for free)',
  ],
  'cobalt': [
    '1:1 Membership Rewards transfer to Aeroplan (Star Alliance), Avios (Oneworld/BA/Iberia), Asia Miles, Flying Blue (Air France/KLM), BA Executive Club',
    'Emergency travel medical — covers entire trip if booked on card',
    'Flight delay insurance — meals/hotel if delayed 4+ hours',
    'Lost & delayed baggage insurance',
    'Purchase protection (90 days) & extended warranty (+1 yr)',
    'Rental car collision/loss damage insurance',
    'Amex Offers — targeted discounts at restaurants, retailers, and travel',
  ],
  'nb-we': [
    'Mastercard Travel Pass (DragonPass) — 3 free lounge visits/yr at 1,300+ lounges',
    'Mobile device insurance for phones purchased on card',
    'Emergency travel medical insurance',
    'Trip cancellation & interruption coverage',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'scotia-gold': [
    'No foreign transaction fees — save 2.5% on all international purchases',
    'Scene+ points redeemable on travel bookings at 1cpp, movies, and statement credit',
    'Emergency travel medical insurance',
    'Trip cancellation & interruption insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'td-aeroplan': [
    'Free first checked bag — you + up to 8 travel companions per Air Canada flight',
    'NEXUS fee rebate — $100 every 4.5 years (covers full application cost)',
    'Preferred boarding on Air Canada flights (Group 2 boarding)',
    'Emergency travel medical — up to 21 days per trip',
    'Trip cancellation, interruption & delayed baggage insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
    'Fee waived with TD All-Inclusive Banking (min $5K balance)',
  ],
  'cibc-aeroplan': [
    'Free first checked bag — you + up to 8 companions per Air Canada flight',
    'Preferred boarding on Air Canada flights (Group 2 boarding)',
    'Emergency travel medical — up to 21 days per trip',
    'Trip cancellation & interruption insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'scotia-passport': [
    'Visa Airport Companion — 6 free lounge visits/yr at 1,300+ airports worldwide',
    'No foreign transaction fees — save 2.5% on all international purchases',
    'Emergency travel medical — up to 25 days per trip (best among cashback/points VIs)',
    'Trip cancellation, interruption & flight delay insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
    'Fee waived with Scotia Ultimate Package (min $4K balance)',
  ],
  'rbc-avion': [
    'Transfer to Aeroplan (Star Alliance — Air Canada, Lufthansa, Singapore Airlines, United)',
    'Transfer to Avios (Oneworld — British Airways, Iberia, Qatar Airways, Cathay Pacific)',
    'Transfer to Asia Miles & BA Executive Club',
    'Emergency travel medical insurance',
    'Trip cancellation & interruption insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'amex-aeroplan': [
    'Aeroplan points redeemable on Air Canada, Lufthansa, Singapore Airlines & 45+ Star Alliance partners',
    'Aeroplan Status Qualifying Miles (SQM) on eligible purchases — helps reach Elite status',
    'Emergency travel medical insurance',
    'Baggage delay & flight delay insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
    'Amex Offers — targeted cashback/bonus deals at restaurants and retailers',
  ],
  'amex-plat': [
    '$200 Annual Travel Credit — flights, hotels, car rental booked via Amex Travel (auto-applied)',
    '$200 Fine Hotels & Resorts credit — prepaid hotel stays booked via Amex (noon check-in, upgrade, breakfast)',
    'NEXUS rebate — $100 application fee reimbursed every 4.5 years',
    'Unlimited Centurion Lounge access — Toronto Pearson Terminal 1, Calgary + 50+ global locations',
    'Unlimited Priority Pass access — 1,300+ airport lounges worldwide (guest fees apply)',
    '1:1 MR transfer to Aeroplan, Avios, Asia Miles, Flying Blue, BA Executive Club',
    'Emergency travel medical — up to 15 days per trip',
    'Trip cancellation, interruption & flight delay insurance',
    'Platinum concierge — 24/7 restaurant reservations, event tickets, travel planning',
    'Purchase protection (90 days) & extended warranty (+1 yr)',
    'Rental car collision/loss damage insurance',
    'Amex Offers — exclusive targeted deals across travel, dining, retail',
  ],
  'westjet-rbc': [
    'Free first checked bag — you + up to 8 companions on every WestJet flight',
    'Annual WestJet companion voucher — round-trip economy or WestJet Plus fare (~$200–$400 value)',
    'Emergency travel medical & trip cancellation insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'tangerine-mc': [
    'Choose 2 (or 3 with direct deposit) cashback categories — change them quarterly via app',
    'Purchase protection (90 days) & extended warranty (+1 yr)',
    'Note: No travel insurance — pair with a card that has travel medical coverage',
  ],
  'amex-gold': [
    '$100 Annual Travel Credit — hotels or flights booked via Amex Travel (auto-applied)',
    '4 complimentary lounge visits/yr — Priority Pass lounges + Centurion Lounges',
    '1:1 MR transfer to Aeroplan, Avios, Asia Miles, Flying Blue, BA Executive Club',
    'Emergency travel medical insurance',
    'Trip cancellation, interruption & flight delay insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
    'Amex Offers — targeted discounts at restaurants, retailers, and travel',
  ],
  'cibc-aventura': [
    'Visa Airport Companion — 4 free lounge visits/yr at 1,300+ airports worldwide',
    'NEXUS fee rebate — $100 every 4.5 years',
    'Emergency travel medical — up to 15 days per trip',
    'Trip cancellation & interruption insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
  'pc-financial': [
    'PC Optimum points — redeemable at Loblaws, Shoppers Drug Mart, No Frills, Zehrs, Real Canadian Superstore',
    'No annual fee, no income requirement — easy to get and keep',
    'Basic purchase protection & warranty',
    'Note: No travel insurance — not suitable as a primary travel card',
  ],
  'brim-we': [
    'No foreign transaction fees — save 2.5% on all international purchases',
    'Brim Marketplace — earn bonus points at select retailers and restaurants via app',
    '$10/month in Brim credits (auto-applied against purchases)',
    'Points transferable to Air France/KLM Flying Blue (SkyTeam)',
    'Emergency travel medical insurance',
    'Purchase protection & extended warranty',
    'Rental car collision/loss damage insurance',
  ],
};

